# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

# no PR triggers
pr: none

pool: 'Self-Hosted'

steps:
- checkout: self

- script: dir $(Build.SourcesDirectory)


- task: VSBuild@1
  displayName: 'build release anycpu db'
  inputs:
    solution: '**\*.sln' 
    platform: 'any cpu'
    configuration: Release
    clean: true
    createLogFile: true

- task: SqlAzureDacpacDeployment@1
  displayName: 'Execute Azure SQL'
  inputs:
    azureSubscription: 'OptumHackathonPipelineConnection'
    ServerName: 'dacpac-demo.database.windows.net'
    DatabaseName: 'RMDB'
    SqlUsername: 'dacpac'
    SqlPassword: 'Azure@111'
    DacpacFile: '$(build.sourcesDirectory)\\bin\\Release\\RMDB.dacpac'
